@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12
start

:User presses down arrow key;

:Retrieve later input;

if () then ([user is already at present])
    :Apply normal styling to input field;
else ([else])
    if () then ([user is navigating back to present])
        :Display empty input;
    else ([else])
        :Display later input;
        :Style input field to show current input is from history;
    endif
endif

stop
@enduml
