@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12
start

:User presses up arrow key;

:Retrieve earlier input;

if () then ([earlier input does not exist])
    :No changes;
else ([else])
    :Display earlier input;
    :Style input field to show current input is from history;
endif

stop
@enduml
